muse/config/routes.rb
Rails.application.routes.draw do
  Rails.application.routes.draw do
    root to: "artists#index"
  
    get "about", to: "application#about"
    get "artists", to: "artists#index"

    get "songs/new", to: "songs#new"
    post "songs", to: "songs#create"
    get "artists/new", to: "artists#new"
    post "artists", to: "artists#create"
    get "artists/:id/edit", to: "artists#edit", as: :artist_edit
    patch "artists/:id", to: "artists#update"
    delete "artists/:id", to: "artists#destroy"

    get "artists/:id", to: "artists#show", as: :artist
  resources :artists , :songs
end

muse/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

muse/app/models/artist.rb
class Artist < ApplicationRecord
    has_many :songs, dependent: :destroy 
    belongs_to :user
end

muse/app/models/song.rb
class Song < ApplicationRecord
  belongs_to :artist
end

muse/app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :artists
end

muse/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

muse/app/controllers/artists_controller.rb
class ArtistsController < ApplicationController
  before_action :authenticate_user!, only: [:new , :edit , :destroy]
  before_action :find_artist, except: [:index, :new, :create]
  def index
    @artists = Artist.all
  end

  def show
    @artist = Artist.find(params[:id])
    @songs = @artist.songs
    if @artist.user !=  current_user
      flash[:notice] = 'Not allowed!'
      redirect_to artists_path
    end
   
  end

  def new
    @artist = Artist.new
  end

  def create
    @artist=Artist.new(person_params)
    @artist.user = current_user
    if @artist.save
        
      redirect_to @artist
     else 
      render 'new'
     end
   
  end

  def edit
    @artist = Artist.find(params[:id])
  end

  def update
    artist = Artist.find(params[:id])
    artist.update(person_params)
      
    redirect_to artist
  end

  def destroy
    Artist.find(params[:id]).destroy
  
    redirect_to artists_path
  end

  private
    
    def person_params
      params.require(:artist).permit(:name, :albums, :hometown, :img)
    end
end

muse/app/controllers/songs_controller.rb
class SongsController < ApplicationController

    def new
        @artist = Artist.find(params[:artist_id])
        @song = Song.new
      end

      
    def create
        puts params
        artist = Artist.find(params[:song][:artist_id])
        Song.create(params.require(:song).permit(:title, :length, :genre, :artist_id))
               
        redirect_to artist
      end


end

muse/app/helpers/application_helper.rb
module ApplicationHelper
end

muse/app/helpers/artists_helper.rb
module ArtistsHelper
end

muse/app/helpers/songs_helper.rb
module SongsHelper
end

muse/app/views/artists/_form.html.erb
<%= form_for @artist do |f| %>
  <div class="input-field col s6">
  	<%= f.label :name, 'Name'%>
  	<%= f.text_field :name%>
  </div>
  <div class="input-field col s6">
  	<%= f.label :albums, 'Albums' %>
  	<%= f.text_field :albums %>
  </div>
  <div class="input-field col s6">
  	<%= f.label :hometown, 'Hometown' %>
  	<%= f.text_field :hometown %>
  </div>
  <div class="input-field col s6">
  	<%= f.label :img, 'Image' %>
  	<%= f.text_field :img %>
  </div>
  <%= f.submit "Submit", :class => "btn waves-effect waves-light" %>
<% end %>

muse/app/views/artists/edit.html.erb
<h1>Edit <%= @artist.name %></h1>

<%= render 'artists/form' %>

muse/app/views/artists/index.html.erb
<h1 class="mt-4 mb-4 text-center">All the Artists</h1>
<div class="col-md-12 text-center">
    <%= link_to "Add an Artist", new_artist_path, { :class => "btn btn-danger rounded-pill" } %>
</div>
<table class="table table-striped table-dark table-borderless table-hover text-center">
  <thead class="thead-dark">
  <tr>
    <th>Artist</th>
    <th>Image</th>
    <th>Albums</th>
    <th>Hometown</th>
    <th>Edit</th>
    <th>Delete</th>
  </tr>
</thead>
<tbody>
  <% @artists.each do |artist| %>
      <tr>
        <td><%= link_to artist.name, artist_path(artist) %></td>
        <td><%= image_tag(artist.img, size: "100x100", alt: "Artist Image") %></td>
        <td><%= artist.albums %></td>
        <td><%= artist.hometown %></td>
        <td><a class="btn btn-danger rounded-pill" href="<%= edit_artist_path(artist) %>" >
           <em class="">Edit Artist</em>
          </a>
        </td>
         <td><a class="btn btn-danger rounded-pill" data-confirm="Are you sure you want to delete <%= artist.name %>?" data-method="delete" href="/artists/<%= artist.id %>" rel="nofollow"><i class="large material-icons">Delete Artist</i>
         </a>
        </td>
      </tr>
  <% end %>
  </tbody>
</table>

muse/app/views/artists/new.html.erb
<h1>New Artist</h1>

<%= render 'artists/form' %>

muse/app/views/artists/show.html.erb
 <h1><%= @artist.name %> Songs</h1>
  <%= link_to "New Song", new_song_path(:artist_id => @artist.id), { :class => "button waves-effect waves-light btn" } %> 
   <br><br>
  <div class="row">
    <% @songs.each do |song| %>

        <div class="card-panel grey lighten-2 col s4" style="margin: 10px">
          <%= image_tag(@artist.img, size: "100x100", alt: "Artist Image") %>
          <br>
          <strong><%= link_to song.title %></strong>
          <em><%= song.genre %></em>
        </div>
    <% end %>
  </div>

muse/app/views/layouts/_nav.html.erb
<nav class="navbar navbar-expand-md navbar-dark bg-dark mb-4">
  <a class="navbar-brand" href="/">Muse</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarCollapse">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item active">
        <%= link_to('Home', artists_path, class: 'nav-item nav-link active') %>
      </li>
      <li class="nav-item active">
        <%= link_to('New artist', new_artist_path, class: 'nav-item nav-link active') %>
      </li>
    </ul>
    <form class="form-inline mt-2 mt-md-0">
      <input class="form-control mr-sm-2" type="text" placeholder="Search" aria-label="Search">
      <button class="btn btn-secondary my-2 my-sm-0" type="submit">Search</button>
    </form>
  </div>
</nav>

muse/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
  <p class="notice"><%= notice %></p>
<p class="alert"><%= alert %></p>

    <title>Muse</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
  </head>

  <body>
    <%= render 'layouts/nav' %>
    <%= yield %>
  </body>
</html>

muse/app/views/songs/_form.html.erb
<%= form_for @song do |f| %>
  <%= f.hidden_field :artist_id, :value => @artist.id %>
  <div class="input-field col s6">
  	<%= f.label :title, 'Title' %>
  	<%= f.text_field :title %>
  </div>
  <div class="input-field col s6">
  	<%= f.label :genre, 'Genre' %>
  	<%= f.text_field :genre %>
  </div>
  <%= f.submit "Submit", :class => "btn waves-effect waves-light" %>
<% end %>

muse/app/views/songs/new.html.erb
<h1>New Song for <%= @artist.name %></h1>

<%= render 'songs/form' %>